#spring:
#  application:
#    name: order-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/serviceorder
#    username: grantjvm_market_shop1
#    password: NAmyVH7hvN22tzd3MYND
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      dialect: org.hibernate.dialect.MySQLDialect
#      hibernate:
#        format_sql: true
#  cloud:
#    compatibility-verifier:
#      enabled: false
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#payment:
#  service.url : http://localhost:8081/
